Repository wailead/next-seo, pull requests merged in 2024-12, with the labels that each got.

#10 ⚙ Setting: husky setting
  .gitignore
  .husky/pre-commit
  .husky/verifyCommitMessage.js
  .lintstagedrc.js
  package.json
  pnpm-lock.yaml
  public/icons/index.ts
Labels: ⚙ Setting, Done

#15 ✨ Feat: 사이즈 계산 함수 추가 #14
  src/app/utils/index.ts
  src/app/utils/styleRatio.ts
  tailwind.config.ts
Labels: ⚙ Setting, Done

#17 📬 Chore: footer 스타일 수정 #16
  src/app/components/footer/footer.tsx
Labels: 📬 Chore

#20 ✨ Feat: pc 헤더 수정 #18
  src/app/components/button/button.tsx
  src/app/components/header/header_pc.tsx
Labels: ✨ Feature

#25 ✨ Feature: footer css 수정
  src/app/components/footer/footer.tsx
Labels: ✨ Feature

#22 ✨ Feature: 인플루언서 mainheader 컴포넌트 UI 구현 #21
  public/images/gray_apple.svg
  public/images/gray_google.svg
  src/app/(route)/influencer/_view/index.ts
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
  src/app/(route)/influencer/page.tsx
Labels: ✨ Feature

#32 ⚙ Setting: ci test #31
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .gitignore
  package.json
  pnpm-lock.yaml
  public/images/index.ts
Labels: ⚙ Setting

#33 ⚙ Setting: CI test #31
  .github/workflows/ci.yml
  .github/workflows/to_main.yml
Labels: ⚙ Setting

#37 ✨ Feat: Campaign 컴포넌트, 모달창 구현 #27
  public/assets/images/Polygon.png
  public/assets/images/close.svg
  public/assets/images/modal_phone.png
  src/app/(route)/influencer/_view/campaign/Campaign.tsx
  src/app/(route)/influencer/_view/campaign/CampaignModal.tsx
  src/app/(route)/influencer/_view/components/CampaignCard.tsx
  src/app/(route)/influencer/_view/index.ts
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
  src/app/(route)/influencer/page.tsx
Labels: ✨ Feature

#43 🐞 Fix: 유튜브 영상 재생되도록 수정 #41
  .github/workflows/ci.yml
  .github/workflows/git-push.yml
  .husky/pre-commit
  .prettierrc
  src/app/(route)/influencer/_view/campaign/Campaign.tsx
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
  src/app/(route)/influencer/_view/marketing-banner/marketing-banner.tsx
  src/app/(route)/influencer/marketing/page.tsx
  src/app/(route)/influencer/page.tsx
  src/app/components/index.ts
Labels: 🐞 Fix

#45 ✨ Feat: 마케팅 배너 추가 #40
  public/icons/icon_arrow_back.svg
  src/app/(route)/influencer/_view/introduction/Introduction.tsx
  src/app/(route)/influencer/_view/marketing-banner/marketing-banner.tsx
  tsconfig.json
Labels: ✨ Feature, Done

#47 ✨ Feat: 와이리 가입하기 배너 #46
  .prettierrc
  public/icons/apple.svg
  public/icons/google.svg
  src/app/(route)/influencer/_view/join-banner/join-banner.tsx
  src/app/(route)/influencer/page.tsx
  src/app/(route)/layout.tsx
Labels: ✨ Feature, Done

#48 🎨 Style: 와이리 가입하기 배너 #46
  .github/workflows/ci.yml
  src/app/(route)/influencer/_view/join-banner/components/app-store-buttons.tsx
  src/app/(route)/influencer/_view/join-banner/components/background-image-box.tsx
  src/app/(route)/influencer/_view/join-banner/components/join-box.tsx
  src/app/(route)/influencer/_view/join-banner/components/phone-image-box.tsx
  src/app/(route)/influencer/_view/join-banner/join-banner.tsx
Labels: 🎨 Style, Done

#55 💻 Structure: 폴더 구조 변경 #52
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
  src/app/(route)/influencer/_view/marketing-banner/MarketingBanner.tsx
  src/app/(route)/influencer/_view/question/Question.tsx
  src/app/components/header/header_mobile.tsx
  src/app/components/header/header_pc.tsx
Labels: 💻 Structure

#59 🎨 Style: px -> rem 으로 변경 #57
  .eslintrc.json
  .github/ISSUE_TEMPLATE/⚡️-feature.md
  .github/ISSUE_TEMPLATE/✅-test.md
  .github/ISSUE_TEMPLATE/🐛-bug.md
  .github/labels.json
  .github/pull_request_template.md
  .lintstagedrc.js
  README.md
  next.config.ts
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  src/app/(route)/advertiser/page.tsx
  src/app/(route)/influencer/_view/campaign/Campaign.tsx
  src/app/(route)/influencer/_view/campaign/CampaignModal.tsx
  src/app/(route)/influencer/_view/campaign/components/CampaignCard.tsx
  src/app/(route)/influencer/_view/introduction/Introduction.tsx
  src/app/(route)/influencer/_view/introduction/components/introductionBox.tsx
  src/app/(route)/influencer/_view/join-banner/JoinBanner.tsx
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
  src/app/(route)/influencer/_view/question/Question.tsx
  src/app/(route)/influencer/_view/question/components/QuestionBox.tsx
  src/app/(route)/influencer/marketing/page.tsx
  src/app/(route)/page.tsx
  src/app/components/footer/footer.tsx
  src/app/components/titleForm/titleForm.tsx
  src/app/utils/styleRatio.ts
  tailwind.config.ts
Labels: ⚙ Setting, 🎨 Style

#63 🔨 Refactor: Image -> CustomImage 로 변경 #62
  src/app/(route)/influencer/_view/campaign/CampaignModal.tsx
  src/app/(route)/influencer/_view/campaign/components/CampaignCard.tsx
  src/app/(route)/influencer/_view/introduction/Introduction.tsx
  src/app/(route)/influencer/_view/join-banner/components/background-image-box.tsx
  src/app/(route)/influencer/_view/join-banner/components/phone-image-box.tsx
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
  src/app/(route)/influencer/_view/marketing-banner/MarketingBanner.tsx
  src/app/components/custom-image/CustomImage.tsx
  src/app/components/footer/footer.tsx
  src/app/components/header/header_mobile.tsx
  src/app/components/header/header_pc.tsx
Labels: 🔨 Refactor

#67 🔨 Refactor: nav 스타일 정상화 #66
  src/app/components/button/LinkButton.tsx
  src/app/components/header/header_mobile.tsx
  src/app/components/header/header_pc.tsx
  src/app/components/index.ts
Labels: 🔨 Refactor

#69 💻 Structure: image 파일 이동 #68
  public/assets/icons/about_image_01.svg
  public/assets/icons/about_image_02.svg
  public/assets/icons/about_image_03.svg
  public/assets/icons/about_image_04.svg
  public/assets/icons/about_image_05.svg
  public/assets/icons/about_image_06.svg
  public/assets/icons/arrow.svg
  public/assets/icons/arrow_active_left.svg
  public/assets/icons/arrow_active_right.svg
  public/assets/icons/arrow_inactive_left.svg
  public/assets/icons/arrow_inactive_right.svg
  public/assets/icons/channel_talk.svg
  public/assets/icons/close.svg
  public/assets/icons/first.svg
  public/assets/icons/our_service_calendar.svg
  public/assets/icons/our_service_computer.svg
  public/assets/icons/our_service_doc.svg
  public/assets/icons/our_service_ellipse.svg
  public/assets/icons/our_service_humans.svg
  public/assets/icons/our_service_medal.svg
  public/assets/icons/our_service_search.svg
  public/assets/icons/plan_false.svg
  public/assets/icons/plan_true.svg
  public/assets/icons/quote.svg
  public/assets/icons/wairi_logo.svg
Labels: 💻 Structure

#71 🔨 Refactor: CustomImage, LinkButton 수정 및 적용 #70
  src/app/(route)/influencer/_view/join-banner/components/app-store-buttons.tsx
  src/app/(route)/influencer/_view/join-banner/components/background-image-box.tsx
  src/app/(route)/influencer/_view/join-banner/components/phone-image-box.tsx
  src/app/(route)/influencer/_view/marketing-banner/MarketingBanner.tsx
  src/app/components/button/LinkButton.tsx
  src/app/components/custom-image/CustomImage.tsx
Labels: 🔨 Refactor

#73 ⚙ Setting: 윈도우 husky 오류 수정 #60
  .husky/commit-msg
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/app/(route)/page.tsx
Labels: ⚙ Setting

#75 ✨ Feat: 이미지 크기 조절 #60
  .eslintrc.json
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
Labels: ✨ Feature

#77 ✨ Feat: campaign 이미지 경로 변경 및 사이즈 조절 #76
  public/icons/influencer/close.svg
  src/app/(route)/influencer/_view/campaign/Campaign.tsx
  src/app/(route)/influencer/_view/campaign/CampaignModal.tsx
  src/app/(route)/influencer/_view/campaign/components/CampaignCard.tsx
Labels: ✨ Feature

#79 ✨ Feat: campaign 모달창 transition 적용 #78
  src/app/(route)/influencer/_view/campaign/Campaign.tsx
  src/app/(route)/influencer/_view/campaign/CampaignModal.tsx
  tailwind.config.ts
Labels: ✨ Feature, Done

#82 ✨ Feat: chat-bot UI 구현 #81
  public/icons/chat_bot.svg
  src/app/(route)/layout.tsx
  src/app/components/chat-bot/ChatBot.tsx
  src/app/components/index.ts
Labels: ✨ Feature, Done

#84 🐞 Fix: 입장, 새로고침 시 modal창이 잠시 보이는 오류 #83
  src/app/(route)/influencer/_view/campaign/CampaignModal.tsx
Labels: 🐞 Fix, Done

#88 ✨ Feat: 광고주 페이지 #86
  public/images/advertiser/logo1/LogoBlueOcean.png
  public/images/advertiser/logo1/LogoCourtyard.png
  public/images/advertiser/logo1/LogoLotte.png
  public/images/advertiser/logo1/LogoPhognix.png
  public/images/advertiser/logo1/LogoPremier.png
  public/images/advertiser/logo1/LogoTheFirst.png
  public/images/advertiser/logo1/LogoTheIsland.png
  public/images/advertiser/logo1/LogoTripCom.png
  public/images/advertiser/logo1/index.ts
  public/images/advertiser/logo2/LogoAvani.png
  public/images/advertiser/logo2/LogoCappuccino.png
  public/images/advertiser/logo2/LogoHotelKoreana.png
  public/images/advertiser/logo2/LogoIbis.png
  public/images/advertiser/logo2/LogoKlook.png
  public/images/advertiser/logo2/LogoNovotel.png
  public/images/advertiser/logo2/LogoTheSpa.png
  public/images/advertiser/logo2/LogoYeosuHotel.png
  public/images/advertiser/logo2/index.ts
  src/app/(route)/(advertiser)/_view/company-banner/CompanyBanner.tsx
  src/app/(route)/(advertiser)/_view/company-banner/components/SlideBanner.tsx
  src/app/(route)/(advertiser)/_view/goverment-banner/GovermentBanner.tsx
  src/app/(route)/(advertiser)/page.tsx
  src/app/components/banner/BannerLayout.tsx
  src/app/components/custom-image/CustomImage.tsx
  src/app/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Feature

#90 ✨ Feat: 배너 hover 시 슬라이드 멈춤 #89
  src/app/(route)/(advertiser)/_view/company-banner/components/SlideBanner.tsx
  src/app/(route)/influencer/page.tsx
  src/app/styles/globals.css
Labels: ✨ Feature

#92 ✨ Feat: more-service 컴포넌트 UI 구현 #85
  public/images/advertiser/more-service/more_service_0.png
  public/images/advertiser/more-service/more_service_1.png
  public/images/advertiser/more-service/more_service_2.png
  public/images/advertiser/more-service/more_service_3.png
  src/app/(route)/(advertiser)/_view/more-service/MoreService.tsx
  src/app/(route)/(advertiser)/_view/more-service/components/ServiceCard.tsx
  src/app/(route)/(advertiser)/page.tsx
  src/app/hooks/index.ts
  src/app/hooks/scroll-button/useScrollButton.ts
Labels: ✨ Feature

#102 ✨ Feat: more-service 컴포넌트 UI 구현 #85
  public/icons/plan_true_gray.svg
  public/icons/plan_true_white.svg
  src/app/(route)/(advertiser)/_view/inquiry/Inquiry.tsx
  src/app/(route)/(advertiser)/_view/inquiry/components/InquiryInput.tsx
  src/app/(route)/(advertiser)/_view/inquiry/components/InquiryRadio.tsx
  src/app/(route)/(advertiser)/page.tsx
  src/app/hooks/index.ts
  src/app/hooks/use-email/use-email.ts
  src/app/hooks/use-phone/use-phone.ts
  src/app/hooks/use-scroll-button/use-scroll-button.ts
Labels: ✨ Feature, 🙋‍♂️ Question

#106 ✨ Feat: more-service 단위 변경 px -> rem #105
  src/app/(route)/(advertiser)/_view/more-service/MoreService.tsx
  src/app/(route)/(advertiser)/_view/more-service/components/ServiceCard.tsx
Labels: ✨ Feature

#110 ✨ Feat: Reference UI 구현 #109
  public/assets/images/reference_menu_image_0.png
  public/assets/images/reference_menu_image_1.png
  public/assets/images/reference_menu_image_2.png
  public/images/advertiser/peference/city/city0.png
  public/images/advertiser/peference/city/city1.png
  public/images/advertiser/peference/city/city2.png
  public/images/advertiser/peference/city/city_main.png
  public/images/advertiser/peference/city/index.ts
  public/images/advertiser/peference/east/east0.png
  public/images/advertiser/peference/east/east1.png
  public/images/advertiser/peference/east/east2.png
  public/images/advertiser/peference/east/east3.png
  public/images/advertiser/peference/east/east_main.png
  public/images/advertiser/peference/east/index.ts
  public/images/advertiser/peference/more/index.ts
  public/images/advertiser/peference/more/more0.png
  public/images/advertiser/peference/more/more1.png
  public/images/advertiser/peference/more/more2.png
  public/images/advertiser/peference/more/more3.png
  public/images/advertiser/peference/more/more4.png
  public/images/advertiser/peference/more/more5.png
  public/images/advertiser/peference/more/more6.png
  public/images/advertiser/peference/more/more7.png
  public/images/advertiser/peference/more/more8.png
  public/images/advertiser/peference/more/more9.png
  public/images/advertiser/peference/pyeongchang/index.ts
  public/images/advertiser/peference/pyeongchang/pyeongchang0.png
  public/images/advertiser/peference/pyeongchang/pyeongchang1.png
  public/images/advertiser/peference/pyeongchang/pyeongchang2.png
  public/images/advertiser/peference/pyeongchang/pyeongchang3.png
  public/images/advertiser/peference/pyeongchang/pyeongchang_main.png
  src/app/(route)/(advertiser)/_view/reference/Reference.tsx
  src/app/(route)/(advertiser)/_view/reference/components/ReferenceCard.tsx
  src/app/(route)/(advertiser)/_view/reference/components/ReferenceSlide.tsx
  src/app/(route)/(advertiser)/page.tsx
  src/app/components/title-form/TitleForm.tsx
  tailwind.config.ts
Labels: ✨ Feature, Done

#111 ✨ Feat: Reference UI 구현 #109
  src/app/(route)/(advertiser)/_view/reference/Reference.tsx
  src/app/(route)/(advertiser)/_view/reference/components/ReferenceCard.tsx
  src/app/(route)/(advertiser)/page.tsx
Labels: ✨ Feature

#112 ✨ Feat: Reference UI 구현 #109
  src/app/(route)/(advertiser)/_view/reference/Reference.tsx
  src/app/components/title-form/TitleForm.tsx
Labels: ✨ Feature

#116 merge to main
  src/app/components/header/header_mobile.tsx
Labels: 🌏 Deploy

#118 HOTFIX: 빌드에러 해결 #117
  src/app/(route)/influencer/_view/introduction/Introduction.tsx
  src/app/(route)/influencer/_view/introduction/components/introduction-box.tsx
Labels: 🌏 Deploy

#123 ✨ Feat: 광고주 페이지 작업
  .github/pull_request_template.md
  src/app/(route)/(advertiser)/_view/company-banner/components/SlideBanner.tsx
  src/app/(route)/(advertiser)/_view/promotion-video/PromotionVideo.tsx
  src/app/(route)/(advertiser)/page.tsx
Labels: ✨ Feature

#126 Merge dev into main
  .github/pull_request_template.md
  src/app/(route)/(advertiser)/_view/about/About.tsx
  src/app/(route)/(advertiser)/_view/about/components/AboutBox.tsx
  src/app/(route)/(advertiser)/_view/company-banner/components/SlideBanner.tsx
  src/app/(route)/(advertiser)/_view/our-services/components/AgencyService.tsx
  src/app/(route)/(advertiser)/_view/performance/Performance.tsx
  src/app/(route)/(advertiser)/_view/promotion-video/PromotionVideo.tsx
  src/app/(route)/(advertiser)/_view/service-introduction/ServiceIntroduction.tsx
  src/app/(route)/(advertiser)/page.tsx
  src/app/(route)/influencer/_view/introduction/Introduction.tsx
  src/app/(route)/influencer/_view/introduction/components/introduction-box.tsx
  src/app/(route)/influencer/page.tsx
  src/app/components/header/Header.tsx
  src/app/styles/globals.css
Labels: 🌏 Deploy

#131 ✨ Feat: Reference UI 구현 (드래그 기능 추가) #109
  src/app/(route)/(advertiser)/_view/reference/components/ReferenceSlide.tsx
Labels: ✨ Feature, 🙋‍♂️ Question

#133 ✨ Feat: mainheader 유튜브 배경 색 수정 #132
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
Labels: ✨ Feature

#138 ✨ Feat: Footer 이미지 크기 조절 #137
  src/app/(route)/(advertiser)/_view/partners/Partners.tsx
  src/app/components/footer/footer.tsx
Labels: ✨ Feature, Done

#140 ✨ Feat: 광고주 페이지 반응형 작업
  src/app/(route)/(advertiser)/_view/company-banner/components/SlideBanner.tsx
  src/app/(route)/(advertiser)/_view/goverment-banner/GovermentBanner.tsx
  src/app/(route)/(advertiser)/_view/promotion-video/PromotionVideo.tsx
  src/app/components/banner/BannerLayout.tsx
  src/app/components/custom-image/CustomImage.tsx
  src/app/components/section-layout/SectionLayout.tsx
  src/app/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature

#151 ✨ Feat: z-index 수정 #150
  src/app/(route)/influencer/_view/campaign/Campaign.tsx
  src/app/(route)/influencer/_view/campaign/CampaignModal.tsx
  src/app/components/header/Header.tsx
Labels: ✨ Feature

#152 ✨ Feat: 인플루언서 반응형 작업 #149
  src/app/(route)/(advertiser)/_view/partners/Partners.tsx
  src/app/(route)/influencer/_view/mainheader/Mainheader.tsx
Labels: ✨ Feature

#153 ✨ Feat: 인플루언서 반응형 작업 #149
  src/app/(route)/influencer/_view/campaign/Campaign.tsx
  src/app/(route)/influencer/_view/campaign/CampaignModal.tsx
  src/app/(route)/influencer/_view/campaign/components/CampaignCard.tsx
  src/app/components/custom-image/CustomImage.tsx
Labels: ✨ Feature

#155 ✨ Feat: footer 반응형 구현 #154
  src/app/components/footer/footer.tsx
Labels: ✨ Feature

#157 ✨ Feat: 광고주 페이지 반응형 구현 #156
  src/app/(route)/(advertiser)/_view/inquiry/Inquiry.tsx
  src/app/(route)/(advertiser)/_view/inquiry/components/InquiryInput.tsx
  src/app/(route)/(advertiser)/_view/inquiry/components/InquiryRadio.tsx
  src/app/components/custom-image/CustomImage.tsx
Labels: ✨ Feature

#158 ✨ Feat: 광고주 페이지 반응형 구현 #156
  src/app/(route)/(advertiser)/_view/more-service/MoreService.tsx
  src/app/(route)/(advertiser)/_view/more-service/components/ServiceCard.tsx
Labels: ✨ Feature

#159 ✨ Feat: 광고주 페이지 반응형 구현 #156
  public/images/advertiser/peference/east/east_main.png
  public/images/advertiser/peference/pyeongchang/pyeongchang_main.png
  src/app/(route)/(advertiser)/_view/reference/Reference.tsx
  src/app/(route)/(advertiser)/_view/reference/components/ReferenceCard.tsx
  src/app/(route)/(advertiser)/_view/reference/components/ReferenceSlide.tsx
  src/app/components/title-form/TitleForm.tsx
Labels: ✨ Feature
